export const blogData = [
    {
        id: 1,
        title: "Wireless Networking Basics",
        category: "Network",
        subCategory: ["Network", "Wireless"],
        content: "The wireless transmissions are achieved with radio waves through the air. The frequency of the radio waves is standardized so that both transmitting and receiving sides can use the same frequency to communicate with each other. This frequency of radio waves is referred to as frequency bands. The two common frequency bands are 2.4GHz and 5GHz bands. 2.4GHz is slower and more susceptible to interference, but has wider reach. 5GHz is on the other hand is faster and less susceptible to interference, but has less reach. Moreover, 2.4GHz are 5 GHz are only a shorthand of where the radio wave could start. If the frequency band is set to 2.4GHz, for instance, the radio wave could fall into anywhere between 2.4GHz and 2.5GHz. As we will discuss below, the specific range within the frequency band is further determined by channels.",
        coverPicture: "../../../../public/image/Blog_Image_1",
        createdDate: "1 May 2023",
    },
    {
        id: 2,
        title: "What Is a Proxy Server?",
        category: "Network",
        subCategory: ["Network", "Computer Science"],
        content: "A proxy server is a server that sits between a client and a server and acts on behalf of the client to access the server. The use of proxy server provides some benefits such as enhanced security and privacy, monitoring and filtering traffic, increasing performance, and so on. There are some types of proxy servers available, but in this article, we will discuss one of the most common ones: a web proxy.",
        coverPicture: "../../../public/image/Blog_Image_2",
        createdDate: "2 May 2023",
    },
    {
        id: 3,
        title: "NAT As Security & IP Preservation Technique",
        category: "Network",
        subCategory: ["Network", "Computer Science"],
        content: "NAT (Network Address Translation) is an indispensable networking technique for two reasons. First, it provides a secure way of configuring IP addresses. Second, it helps us not to deplete the remaining available IPv4 addresses, which are a very scarce resource today.",
        coverPicture: "../../../public/image/Blog_Image_3",
        createdDate: "3 May 2023",
    },
    {
        id: 4,
        title: "DHCP Discovery Process",
        category: "Network",
        subCategory: ["Network", "Computer Science"],
        content: "In order for a computer to work, we need to configure four things: 1) an IP address, 2) a subnet mask, 3) a primary gateway, and 4) a DNS server. Let’s say that you are an IT administrator in a company, and you have to configure 100 computers at once. You can probably have the same subnet mask, primary gateway, and a DNS server for the lot. However, IP addresses have to be different for each computer. It would be a nightmare for you to configure it one by one. You need to rely on a system which does the job automatically. This is where a DHCP server comes into the picture. Let’s learn about what it is and what the process of DHCP discovery (meaning the process of assigning an IP address to a node) looks like.",
        coverPicture: "../../../public/image/Blog_Image_4",
        createdDate: "4 May 2023",
    },
    {
        id: 5,
        title: "The TCP/IP Five-Layer Network Model",
        category: "Network",
        subCategory: ["Network", "Computer Science"],
        content: "There are some models that explain how devices communicate with each other on the Internet. One of the most popular ones is TCP/IP five-layer network model. When the information travels from one end to another, packets travel across five different layers, defined by different protocols used. Let’s look at each layer, starting from the bottom of the stack.",
        coverPicture: "../../../public/image/Blog_Image_5",
        createdDate: "5 May 2023",
    },
    {
        id: 6,
        title: "The Physical Layer: Cables, Ports, and Technologies behind",
        category: "Network",
        subCategory: ["Network", "Computer Science"],
        content: "Cat 5, Cat 5e, and Cat 6 cables are the most common copper cables out there today. They are short for Category 5, and Category 6 cables respectively. They look very similar to our naked eyes, but their constructs differ, resulting in different usable lengths and transfer rates. Cat 5 is the oldest of all and has been replaced by Cat 5e and 6. Cat 5e and 6 are made in a way to reduce crosstalk (electric charge is erroneously detected by another wire, causing network error). Following stricter specifications, Cat 6 is the most reliable cable of all. However, because of its structure, its maximum distance is shorter than Cat 5e.",
        coverPicture: "../../../public/image/Blog_Image_6",
        createdDate: "6 May 2023",
    },
    {
        id: 7,
        title: "Data Link Layer: What is a MAC address made up of?",
        category: "Network",
        subCategory: ["Network", "Computer Science"],
        content: "MAC addresses are 12 digits (48 bits or 6 bytes) numbers with separation colons between each two-digit. They utilise hexadecimal (sixteen) numbers with 0 to 9, followed by A to F. The format of a MAC address typically looks like the below: The first six digits are called OUI (Organizationally Unique Identifier) and are determined by the manufacturer of the device. The latter half of a MAC address is unique to the device. When you want to identify a device’s manufacturer, you can look it up online by searching for the OUI of a MAC address. But be careful not to type the latter half of the MAC address for privacy and security reasons.",
        coverPicture: "../../../public/image/Blog_Image_7",
        createdDate: "7 May 2023",
    },
    {
        id: 8,
        title: "What is Unicast, Multicast, Broadcast, or Anycast?",
        category: "Network",
        subCategory: ["Network", "Computer Science"],
        content: "Unicast is a term describing a one-to-one transmission. When we send packets from one device directly to another, it is unicast. For example, client-server architecture (a computer requesting a server for information), transmissions between two computers, or between servers fall into unicast.",
        coverPicture: "../../../public/image/Blog_Image_8",
        createdDate: "8 May 2023",
    },
    {
        id: 9,
        title: "Data Link Layer: Dissecting Ethernet Frame",
        category: "Network",
        subCategory: ["Network", "Computer Science"],
        content: "At the top of the stack, we have the application layer. Here, we have a message that we want to send across the Internet to the destination computer. When the message is sent out to the transport layer, the message is put in an envelope with the information needed for the next layer to process data. This envelope then reaches the next layer at the network layer where another envelope is added on top. Until the physical layer, this process is repeated, encapsulating itself multiple times. ",
        coverPicture: "../../../public/image/Blog_Image_9",
        createdDate: "9 May 2023",
    },
];